#ifndef _STATUS_CODES_H_
#define _STATUS_CODES_H_

#define STATUS_OK 200
#define STATUS_NO_RESPONSE 204
#define STATUS_MOVED 301
#define STATUS_FOUND 302
#define STATUS_METHOD 303
#define STATUS_NOT_MODIFIED 304
#define STATUS_BAD_REQUEST 400
#define STATUS_UNAUTHORIZED 401
#define STATUS_PAYMENT_REQUIRED 402
#define STATUS_FORBIDDEN 403
#define STATUS_NOT_FOUND 404
#define STATUS_INTERNAL_ERROR 500
#define STATUS_NOT_IMPLEMENTED 501

#endif
